### ISSUE TITLE
[1.14.4] Feature request- config to disable nether star fragments.

### ISSUE THREAD

**Issue by ProsperCraft** [kwpugh/veggie_way_forge#1]
I don't want my pack to drop nether star fragments please add a config, with an option to disable resourceful drops.

**Comment by kwpugh** [comment]
Hi,

Actually, I am planning to strip the Resourceful tools out of Veggie Way and make it a separate mod.   

The next version of Veggie Way tonight won’t have the tools.

Regards.

**Comment by ProsperCraft** [comment]
Fantastic thank you!

**Comment by kwpugh** [comment]
Resourceful Tools have been removed as of v24.   They are now in a separate mod.
