### ISSUE TITLE
Carb powder does not appear to work anymore, potatoes/drying agent now gives vitamin powder

### ISSUE THREAD

**Issue by utoc** [kwpugh/veggie_way_forge#11]
Hi there,

Using Veggie Way ``TheVeggieWay-1.15.2-2.1.33`` with Forge ``forge-1.15.2-31.1.63.jar`` we no longer have access to Carb Powder.  It appears that the forge tag forge:carbs is absent from the humble potato.  See attached screenshot:

![forge-crop](https://user-images.githubusercontent.com/11995956/80847689-3532b800-8bd6-11ea-8faf-3bcfd502bc02.png)

Cheers

**Comment by kwpugh** [comment]
I'll take a looksie

**Comment by kwpugh** [comment]
Fixed in v34

**Comment by jjubenv** [comment]
I updated to v34, but still no Carb Powder:
![2020-05-02_10 19 32](https://user-images.githubusercontent.com/6698838/80866850-09a7e000-8c5f-11ea-87e6-c890ba047287.png)
![2020-05-02_10 20 49](https://user-images.githubusercontent.com/6698838/80866864-12001b00-8c5f-11ea-9df9-3416a9907163.png)
![2020-05-02_10 20 53](https://user-images.githubusercontent.com/6698838/80866867-162c3880-8c5f-11ea-8be4-f6d48c68e825.png)

**Comment by kwpugh** [comment]
![Screen Shot 2020-05-02 at 10 16 18 AM](https://user-images.githubusercontent.com/8809210/80868109-0cee9c00-8c5e-11ea-9d22-ee670192a950.png)

It works fine on my end.  Please post a list of other mods you are using.  It may be some sort of tag conflict

**Comment by kwpugh** [comment]
![2020-05-02_10 13 46](https://user-images.githubusercontent.com/8809210/80868138-35769600-8c5e-11ea-8604-ce91e8d61344.png)

**Comment by jjubenv** [comment]
I'm using All The Mods 5 v 1.21  https://www.curseforge.com/minecraft/modpacks/all-the-mods-5/files/2945035.  I updated The Veggie Way manually by replacing v33.  The bug happens in my fresh single player world.

**Comment by kwpugh** [comment]
I will download the pack and take a look.

**Comment by kwpugh** [comment]
For the time being, I am removing recipes that use Forge Tags for powders (other mods fruits, vegetables, etc.).   I may add more of my own crops to make up for it.
