### ISSUE TITLE
Fabric Port 

### ISSUE THREAD

**Issue by Linguardium** [kwpugh/veggie_way_forge#12]
I cant PR to a branch that doesnt exist, but i have a working fabric port forked and dev'd on the Fabric-1.15 branch of my fork.  https://github.com/Linguardium/VeggieWay/tree/Fabric-1.15

If you wouldnt mind testing, that would be great :)
Also, not sure what you did with the single use hand scraper as you hadnt pulled that in at the time of my porting, so i have it set to 20 durability just for testing sake

**Comment by kwpugh** [comment]
I appreciate the porting work, but I'm not sure what to do with it.   I am very awkward with PRs.  I mostly use GitHub for sharing my code and as a backup to my local computer and issue tracking.   Every time someone does a PR for lang translation I manage to screw it up and cut-n-paste- the contents locally and reset the branch, ugg.

I will try to figure something out.


Thank you.

**Comment by kwpugh** [comment]
Oh, and I don't mix forge and fabric together, seems to give me heartburn.

**Comment by kwpugh** [comment]
Oh boy, I'm going to learn quite a few things in your port that I had not figured out yet, especially configs and containers in the crafting grid.

**Comment by kwpugh** [comment]
How do you want me to credit you on the Curseforge project?   This is a new situation for me, I have been running solo the whole time.

**Comment by kwpugh** [comment]
![Screen Shot 2020-05-01 at 9 09 40 PM](https://user-images.githubusercontent.com/8809210/80852694-1e00c400-8bf0-11ea-8457-9319bd47826d.png)

Plant render problem

**Comment by kwpugh** [comment]
New project here:   https://github.com/kwpugh/VeggieWayFabric/tree/1.15.2

**Comment by kwpugh** [comment]
You did a wonder job, a few things beyond my ability that I will have to study.

Besides the plant rendering, the only other things not working seems to be the large pot, it does not stay in the crafting grid.  It should behave like a vanilla bucket in that regard.

**Comment by kwpugh** [comment]
Getting these block state errors:  https://gist.github.com/kwpugh/654e136474f61f8df18daefbd0caa753

Looking to see if I can figure it out.

**Comment by kwpugh** [comment]
![Screen Shot 2020-05-01 at 9 47 00 PM](https://user-images.githubusercontent.com/8809210/80853412-56a39c00-8bf6-11ea-9742-8287e0cbb3d4.png)

Back in business on the plants, fixed a few missing.

Any idea about the Large Pot?

**Comment by Linguardium** [comment]
Thought i took care of it like the mill. I guess make sure the interface is there. I will take a look tomorrow

Actually, that ine should be handled in the item creation settings as a reciperemainder

**Comment by kwpugh** [comment]
The large pot is different, in that it doesn't take damage, but stays in the crafting grid.

I'm going to just switch to a vanilla bucket and drop the large pot for now.

**Comment by Linguardium** [comment]
i fixed the pot, btw
the plant issues were because you had translation keys that werent matching the block. i figured you would want to keep the translation keys as-is rather than bothering whatever translator/translation service you use, so i changed the block id.

**Comment by kwpugh** [comment]
To fix the plants, I had to add the VeggieWayClient to the fabric.mod.json, add a call to the BlockRenders class in the VeggieWayClient.  That seemed to do it.

**Comment by kwpugh** [comment]
The large Pot is dropped, I'm going with a vanilla bucket with water instead.  Thank you anyway.

And thanks again for the porting work.
