### ISSUE TITLE
LargePot can return Empty Item Stack

### ISSUE THREAD

**Issue by cj3636** [kwpugh/veggie_way_forge#14]
https://github.com/kwpugh/VeggieWay/blob/1.15/src/main/java/com/kwpugh/veggie_way/items/ItemLargePot.java#L33-L41

Has the potential to return an empty item stack.

Causing EMC mapping issues with projectE.

**Comment by kwpugh** [comment]
fixed in next release.  Switched to vanilla water bucket

**Comment by kwpugh** [comment]
v38
