### ISSUE TITLE
Hand Scraper dupe bug

### ISSUE THREAD

**Issue by Exoisms** [kwpugh/veggie_way_forge#16]
When combining 2 hand scrapers together to repair (whether they're damaged or not), you get the repaired item plus keep the 2 original hand scrapers back (3 total).  Of course, shift-clicking the repaired item will fill your inventory with hand scrapers.

This was noticed in the latest version of All The Mods 5 (Forge: 31.2.0, TheVeggieWay: 2.1.33).

I also tested it by itself with no other mods and in the latest forge and the latest Mod version and had the same results (Forge: 31.2.0, TheVeggieWay: 2.1.42).

**Comment by kwpugh** [comment]
Interesting.   I tried this with v42 and it does bot dup.   I tried this in both an anvil and in a grindstone and no dups when removing the repaired scrapper from the output slot.

**Comment by kwpugh** [comment]
I fired up the latest All the Mods and the dup doesn't happen either.   Could you provide more specifics on what you are doing?   Are you using something other than the anvil or the grindstone to repair?

**Comment by kwpugh** [comment]
Oh, I see, you mean crafting table repair.  Got it.

**Comment by kwpugh** [comment]
I see the problem.   Will be fixed in v43.

**Comment by Exoisms** [comment]
Sorry for not being more clear, and good deal. 😀
