### ISSUE TITLE
[1.16.3] 2 blaze powder for 1 blaze rod is too cheap and leads to duping.

### ISSUE THREAD

**Issue by ProsperCraft** [kwpugh/veggie_way_forge#21]
The other mods - Silents mechanisms, Immersive Engineering produce 4 powder from one rod, which means if you craft the 2 powder back to a rod, you can magically produce more rods, please adjust the recipie to be 4 for 1 rod, or remove.

**Comment by kwpugh** [comment]
Makes sense, didn't know they were doing 4 powder per rod.   Will be updated shortly.

**Comment by kwpugh** [comment]
Fixed in v2.2.7
