### ISSUE TITLE
[1.18.2] Mod Crash with Forge 1.18.2-40.0.19

### ISSUE THREAD

**Issue by lays24mc** [kwpugh/veggie_way_forge#23]
Hi,

my game crash with this mod on version 2.4.7 and forge 40.0.19. Here the crashlog: https://pastebin.com/3MhgwgRX

**Comment by kwpugh** [comment]
I think this is an issue with farming for Blockheads.  If you disable  VeggieWay, does it still crash?

**Comment by kwpugh** [comment]
May be related  to this one:  https://github.com/ModdingForBlockheads/FarmingForBlockheads/issues/146

I can't even  run FFB.

**Comment by lays24mc** [comment]
I tested it. It works without FFB. So it really seems to be the FFB.

**Comment by kwpugh** [comment]
VeggieWay runs fine without FFB installed.

**Comment by kwpugh** [comment]
yeah, I think this is a FFB issue.
