### ISSUE TITLE
Cactus pie has a recipe issue

### ISSUE THREAD

**Issue by whiteeagle1985** [kwpugh/veggie_way_forge#27]
When you look up the recipe for cactus pie, there is an barrier instead of flour because of an empty tag. I believe it should be either forge:flour or veggie_way:flour instead of the current c:flour tag.

This is in version 2.5.7 of the mod for Forge for Minecraft 1.19.2. Thanks for when you fix this!

**Comment by ArcticAbyss1979** [comment]
mod version 2.6.1
NeoForge for Minecraft 1.20.1
still exists
![image](https://github.com/kwpugh/veggie_way_forge/assets/132092994/99f639b2-65a7-4e35-b1d1-6467979525bf)

**Comment by kwpugh** [comment]
I pushed fixed versions up to curseforge.com, they should approve shortly.
