### ISSUE TITLE
Changed to Closed-Source

### ISSUE THREAD

**Issue by wendall911** [kwpugh/veggie_way_forge#30]
Hi, just a question for clarity. I have supported Veggie Way for our mods, as it has been open-source. Did you change to some closed-source model? Just needing to understand why no source for anything past 1.19

**Comment by kwpugh** [comment]
The mods license has not changed but I have not published any sources due to recurrent issues syncing my code to GitHub.

What is it you are looking for?

**Comment by wendall911** [comment]
Actually, to be able to support mods, the source code should be available somewhere. I can't even file reports if I can't inspect code in any way. I literally cannot support mods that aren't open source. No published sources is essentially "closed-source". I'm not meaning to be obtuse about this, just the reality of even being able to support stuff, as there are a ton of janky mods out there, so I avoid anything that I can't actually see code for. A big motivator for this is when users submit bug reports and I need to see if it is something I'm doing or the other mod. If no source is available, then I am stuck with no ability to debug.

I'd be happy to help with git if you need it.

**Comment by kwpugh** [comment]
Sorry, that really doesn't jive with reality.  90%+ bugs are simply reported but users that never look at source code.  Finding and fixing the bugs is my job.  Now, it is nice when a bug is reported and the reporter cites a line code in question but it is hardly required.  I understand if you only want to use mods that are open source, that is your call.  There are other mods similar to Veggie Way, so there are plenty options.

Regards.

**Comment by wendall911** [comment]
It isn't really my reality, it's the reality of the MIT license. I require open source mods to actually provide sources so I can provide support to users and the broader community. Currently we only have two mods with direct support and a couple modpacks where I will continue to attempt to support. I will just turn users away if there are issues. It is unfortunate that something as simple as pushing code up, or including a sources jar in your build is too much effort. I honestly meant that I'm willing to help. I don't mean this as offensive, but it is very disappointing response to something that literally all other open source mods do as a requirement of the license.
